'use client';

import { useGetNotificationsQuery, useMarkAsReadMutation } from '@/store/features/notification/notificationApi';
import { AlertTriangle, ArrowLeft, CheckCircle, CircleAlert, Clock, Info } from 'lucide-react';
import { useParams, useRouter } from 'next/navigation';
import { useEffect } from 'react';
import { getTranslation } from '@/i18n';

const severityConfig = {
    info: { icon: Info, color: 'text-blue-500', bg: 'bg-blue-50 dark:bg-blue-900/20' },
    success: { icon: CheckCircle, color: 'text-emerald-500', bg: 'bg-emerald-50 dark:bg-emerald-900/20' },
    warning: { icon: AlertTriangle, color: 'text-amber-500', bg: 'bg-amber-50 dark:bg-amber-900/20' },
    critical: { icon: CircleAlert, color: 'text-red-500', bg: 'bg-red-50 dark:bg-red-900/20' },
};

export default function NotificationDetailPage() {
    const { t } = getTranslation();
    const { id } = useParams();
    const router = useRouter();
    const notificationId = Number(id);

    // We can fetch the list again or you can use a separate getNotificationById if your API supports it.
    // Assuming the user navigates here from the list where the cache is already populated
    const { data: notificationsData, isLoading } = useGetNotificationsQuery({ per_page: 50 });
    const [markAsRead] = useMarkAsReadMutation();

    const notification = notificationsData?.data?.items?.find((n) => n.id === notificationId);

    useEffect(() => {
        // Mark as read immediately when opening the page
        if (notification && !notification.is_read) {
            markAsRead(notification.id).catch(console.error);
        }
    }, [notification, markAsRead]);

    if (isLoading) {
        return (
            <div className="panel flex min-h-[400px] items-center justify-center">
                <span className="m-auto mb-10 inline-block h-10 w-10 animate-spin rounded-full border-4 border-transparent border-l-primary border-r-primary align-middle"></span>
            </div>
        );
    }

    if (!notification) {
        return (
            <div className="panel flex min-h-[400px] flex-col items-center justify-center text-center">
                <CircleAlert className="mb-4 h-12 w-12 text-gray-400" />
                <h3 className="mb-2 text-xl font-semibold dark:text-white-light">Notification Not Found</h3>
                <p className="mb-6 text-gray-500">The notification you are looking for does not exist or has been deleted.</p>
                <button type="button" className="btn btn-primary" onClick={() => router.push('/notifications')}>
                    Back to List
                </button>
            </div>
        );
    }

    const config = severityConfig[notification.severity] || severityConfig.info;
    const SeverityIcon = config.icon;

    return (
        <div className="panel flex h-full min-h-[calc(100vh-150px)] flex-col">
            <div className="mb-6 flex items-center justify-between border-b pb-4 dark:border-gray-800">
                <button type="button" className="btn btn-outline-primary btn-sm flex items-center gap-2" onClick={() => router.push('/notifications')}>
                    <ArrowLeft className="h-4 w-4" />
                    Back
                </button>
            </div>

            <div className="flex flex-col gap-6 md:flex-row md:items-start md:gap-8">
                <div className="flex-1">
                    <div className="mb-2 flex flex-wrap items-center gap-2">
                        <span className="inline-flex items-center rounded-md bg-gray-100 px-2.5 py-0.5 text-xs font-semibold text-gray-800 dark:bg-gray-800 dark:text-gray-300">
                            {notification.type_label}
                        </span>
                        <span className={`inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-semibold capitalize ${config.color} ${config.bg}`}>{notification.severity}</span>
                    </div>

                    <h1 className="mb-3 text-2xl font-bold text-gray-900 dark:text-white-light md:text-3xl">{notification.title}</h1>

                    <div className="mb-8 flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                        <Clock className="h-4 w-4" />
                        <span>{notification.created_at_human}</span>
                    </div>

                    <div className="prose max-w-none text-gray-800 dark:prose-invert dark:text-gray-200">
                        {/* Render HTML content generated by react-quill */}
                        <div dangerouslySetInnerHTML={{ __html: notification.message }} className="quill-content" />
                    </div>

                    {notification.action_url && (
                        <div className="mt-8 border-t pt-6 dark:border-gray-800">
                            <a href={notification.action_url} className="btn btn-primary inline-flex items-center gap-2">
                                View Details
                            </a>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
