import { OperationalReportField } from './OperationalReportPage';
import {
    useGetAuditActivityReportMutation,
    useGetCashClosingReportMutation,
    useGetCustomerStatementReportMutation,
    useGetDiscountReportMutation,
    useGetEmployeeSalesReportMutation,
    useGetPaymentSummaryReportMutation,
    useGetStockMovementReportMutation,
    useGetSupplierStatementReportMutation,
    useGetTransferLedgerReportMutation,
} from '@/store/features/reports/reportApi';

export interface OperationalReportConfig {
    title: string;
    description: string;
    fileName: string;
    icon: 'cash' | 'payment' | 'employee' | 'stock' | 'discount' | 'statement' | 'transfer' | 'audit';
    useReportMutation: any;
    fields: OperationalReportField[];
    summaryFields: OperationalReportField[];
    defaultSort?: string;
}

export const operationalReportConfigs = {
    cashClosing: {
        title: 'lbl_report_cash_closing_title',
        description: 'msg_report_cash_closing_desc',
        fileName: 'cash_closing_report',
        icon: 'cash',
        useReportMutation: useGetCashClosingReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'records', label: 'lbl_closings', type: 'number' },
            { key: 'expected_cash', label: 'lbl_expected_cash', type: 'money' },
            { key: 'actual_cash', label: 'lbl_counted_cash', type: 'money' },
            { key: 'difference', label: 'lbl_difference', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'user_name', label: 'lbl_cashier' },
            { key: 'closing_date', label: 'lbl_closing_date' },
            { key: 'opening_cash', label: 'lbl_opening_cash', type: 'money' },
            { key: 'cash_sales', label: 'lbl_cash_sales', type: 'money' },
            { key: 'cash_expense', label: 'lbl_cash_expense', type: 'money' },
            { key: 'due_collection', label: 'lbl_due_collection', type: 'money' },
            { key: 'supplier_payment', label: 'lbl_supplier_payment', type: 'money' },
            { key: 'expected_cash', label: 'lbl_expected_cash', type: 'money' },
            { key: 'actual_cash', label: 'lbl_counted_cash', type: 'money' },
            { key: 'difference', label: 'lbl_difference', type: 'money' },
            { key: 'status', label: 'lbl_status', sortable: true },
            { key: 'created_at', label: 'lbl_created_at', type: 'date', sortable: true },
        ],
    },
    paymentSummary: {
        title: 'lbl_report_payment_summary_title',
        description: 'msg_report_payment_summary_desc',
        fileName: 'payment_summary_report',
        icon: 'payment',
        useReportMutation: useGetPaymentSummaryReportMutation,
        defaultSort: 'total_amount',
        summaryFields: [
            { key: 'methods', label: 'lbl_rows', type: 'number' },
            { key: 'transaction_count', label: 'lbl_transactions', type: 'number' },
            { key: 'total_amount', label: 'lbl_total_amount', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'source_type', label: 'lbl_source' },
            { key: 'payment_method', label: 'lbl_payment_mode', sortable: true },
            { key: 'transaction_count', label: 'lbl_transactions', type: 'number', sortable: true },
            { key: 'total_amount', label: 'lbl_amount', type: 'money', sortable: true },
        ],
    },
    employeeSales: {
        title: 'lbl_report_employee_sales_title',
        description: 'msg_report_employee_sales_desc',
        fileName: 'employee_sales_report',
        icon: 'employee',
        useReportMutation: useGetEmployeeSalesReportMutation,
        defaultSort: 'gross_sales',
        summaryFields: [
            { key: 'employees', label: 'lbl_employees', type: 'number' },
            { key: 'orders', label: 'lbl_orders', type: 'number' },
            { key: 'gross_sales', label: 'lbl_gross_sales', type: 'money' },
            { key: 'amount_collected', label: 'lbl_collected', type: 'money' },
            { key: 'discount_amount', label: 'lbl_discount', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'employee_name', label: 'lbl_employee', sortable: true },
            { key: 'order_count', label: 'lbl_orders', type: 'number', sortable: true },
            { key: 'gross_sales', label: 'lbl_gross_sales', type: 'money', sortable: true },
            { key: 'amount_collected', label: 'lbl_collected', type: 'money' },
            { key: 'discount_amount', label: 'lbl_discount', type: 'money' },
            { key: 'due_amount', label: 'lbl_due', type: 'money' },
        ],
    },
    stockMovement: {
        title: 'lbl_report_stock_movement_title',
        description: 'msg_report_stock_movement_desc',
        fileName: 'stock_movement_ledger',
        icon: 'stock',
        useReportMutation: useGetStockMovementReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'movements', label: 'lbl_movements', type: 'number' },
            { key: 'total_quantity', label: 'lbl_quantity', type: 'number' },
            { key: 'total_amount', label: 'lbl_amount', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'product_name', label: 'lbl_product' },
            { key: 'movement_type', label: 'lbl_movement_type' },
            { key: 'quantity', label: 'lbl_quantity', type: 'number' },
            { key: 'price', label: 'lbl_unit_price', type: 'money' },
            { key: 'total_amount', label: 'lbl_amount', type: 'money' },
            { key: 'reference_no', label: 'lbl_reference' },
            { key: 'reason', label: 'lbl_reason' },
            { key: 'user_name', label: 'lbl_created_by' },
            { key: 'created_at', label: 'lbl_created_at', type: 'date', sortable: true },
        ],
    },
    discount: {
        title: 'lbl_report_discount_title',
        description: 'msg_report_discount_desc',
        fileName: 'discount_report',
        icon: 'discount',
        useReportMutation: useGetDiscountReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'orders', label: 'lbl_orders', type: 'number' },
            { key: 'discount_amount', label: 'lbl_discount', type: 'money' },
            { key: 'gross_sales', label: 'lbl_gross_sales', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'invoice', label: 'lbl_invoice' },
            { key: 'customer_name', label: 'lbl_customer' },
            { key: 'user_name', label: 'lbl_cashier' },
            { key: 'subtotal', label: 'lbl_subtotal', type: 'money' },
            { key: 'discount_amount', label: 'lbl_discount', type: 'money' },
            { key: 'grand_total', label: 'lbl_total', type: 'money' },
            { key: 'created_at', label: 'lbl_created_at', type: 'date', sortable: true },
        ],
    },
    customerStatement: {
        title: 'lbl_report_customer_statement_title',
        description: 'msg_report_customer_statement_desc',
        fileName: 'customer_statement_report',
        icon: 'statement',
        useReportMutation: useGetCustomerStatementReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'entries', label: 'lbl_entries', type: 'number' },
            { key: 'debit', label: 'lbl_due', type: 'money' },
            { key: 'credit', label: 'lbl_paid', type: 'money' },
            { key: 'balance', label: 'lbl_balance', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'party_name', label: 'lbl_customer', sortable: true },
            { key: 'entry_type', label: 'lbl_type' },
            { key: 'debit', label: 'lbl_due', type: 'money', sortable: true },
            { key: 'credit', label: 'lbl_paid', type: 'money', sortable: true },
            { key: 'balance', label: 'lbl_balance', type: 'money', sortable: true },
            { key: 'status', label: 'lbl_status' },
            { key: 'created_at', label: 'lbl_created_at', type: 'date', sortable: true },
        ],
    },
    supplierStatement: {
        title: 'lbl_report_supplier_statement_title',
        description: 'msg_report_supplier_statement_desc',
        fileName: 'supplier_statement_report',
        icon: 'statement',
        useReportMutation: useGetSupplierStatementReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'entries', label: 'lbl_entries', type: 'number' },
            { key: 'debit', label: 'lbl_purchase', type: 'money' },
            { key: 'credit', label: 'lbl_paid', type: 'money' },
            { key: 'balance', label: 'lbl_balance', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'party_name', label: 'lbl_supplier', sortable: true },
            { key: 'entry_type', label: 'lbl_type' },
            { key: 'debit', label: 'lbl_purchase', type: 'money', sortable: true },
            { key: 'credit', label: 'lbl_paid', type: 'money', sortable: true },
            { key: 'balance', label: 'lbl_balance', type: 'money', sortable: true },
            { key: 'status', label: 'lbl_status' },
            { key: 'created_at', label: 'lbl_created_at', type: 'date', sortable: true },
        ],
    },
    transferLedger: {
        title: 'lbl_report_transfer_ledger_title',
        description: 'msg_report_transfer_ledger_desc',
        fileName: 'transfer_ledger_report',
        icon: 'transfer',
        useReportMutation: useGetTransferLedgerReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'transfers', label: 'lbl_transfers', type: 'number' },
            { key: 'items', label: 'lbl_items', type: 'number' },
            { key: 'quantity', label: 'lbl_quantity', type: 'number' },
        ],
        fields: [
            { key: 'from_store', label: 'lbl_from_store' },
            { key: 'to_store', label: 'lbl_to_store' },
            { key: 'status', label: 'lbl_status', sortable: true },
            { key: 'item_count', label: 'lbl_items', type: 'number' },
            { key: 'total_quantity', label: 'lbl_quantity', type: 'number' },
            { key: 'created_by', label: 'lbl_created_by' },
            { key: 'shipped_at', label: 'lbl_shipped_at', type: 'date' },
            { key: 'received_at', label: 'lbl_received_at', type: 'date' },
            { key: 'created_at', label: 'lbl_created_at', type: 'date', sortable: true },
        ],
    },
    auditActivity: {
        title: 'lbl_report_audit_activity_title',
        description: 'msg_report_audit_activity_desc',
        fileName: 'audit_activity_report',
        icon: 'audit',
        useReportMutation: useGetAuditActivityReportMutation,
        defaultSort: 'created_at',
        summaryFields: [{ key: 'events', label: 'lbl_events', type: 'number' }],
        fields: [
            { key: 'store_name', label: 'lbl_store', sortable: true },
            { key: 'actor_name', label: 'lbl_user' },
            { key: 'action', label: 'lbl_action' },
            { key: 'entity_type', label: 'lbl_entity' },
            { key: 'entity_id', label: 'lbl_entity_id', type: 'number' },
            { key: 'entity_label', label: 'lbl_reference' },
            { key: 'ip_address', label: 'lbl_ip_address' },
            { key: 'created_at', label: 'lbl_created_at', type: 'date', sortable: true },
        ],
    },
} satisfies Record<string, OperationalReportConfig>;
