import { OperationalReportField } from './OperationalReportPage';
import {
    useGetAuditActivityReportMutation,
    useGetCashClosingReportMutation,
    useGetCustomerStatementReportMutation,
    useGetDiscountReportMutation,
    useGetEmployeeSalesReportMutation,
    useGetPaymentSummaryReportMutation,
    useGetStockMovementReportMutation,
    useGetSupplierStatementReportMutation,
    useGetTransferLedgerReportMutation,
} from '@/store/features/reports/reportApi';

export interface OperationalReportConfig {
    title: string;
    description: string;
    fileName: string;
    icon: 'cash' | 'payment' | 'employee' | 'stock' | 'discount' | 'statement' | 'transfer' | 'audit';
    useReportMutation: any;
    fields: OperationalReportField[];
    summaryFields: OperationalReportField[];
    defaultSort?: string;
}

export const operationalReportConfigs = {
    cashClosing: {
        title: 'Cash Register / Shift Closing Report',
        description: 'Opening cash, cash sales, expenses, expected cash, counted cash, and shortage or overage.',
        fileName: 'cash_closing_report',
        icon: 'cash',
        useReportMutation: useGetCashClosingReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'records', label: 'Closings', type: 'number' },
            { key: 'expected_cash', label: 'Expected Cash', type: 'money' },
            { key: 'actual_cash', label: 'Counted Cash', type: 'money' },
            { key: 'difference', label: 'Difference', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'user_name', label: 'Cashier' },
            { key: 'closing_date', label: 'Closing Date' },
            { key: 'opening_cash', label: 'Opening Cash', type: 'money' },
            { key: 'cash_sales', label: 'Cash Sales', type: 'money' },
            { key: 'cash_expense', label: 'Cash Expense', type: 'money' },
            { key: 'due_collection', label: 'Due Collection', type: 'money' },
            { key: 'supplier_payment', label: 'Supplier Payment', type: 'money' },
            { key: 'expected_cash', label: 'Expected Cash', type: 'money' },
            { key: 'actual_cash', label: 'Counted Cash', type: 'money' },
            { key: 'difference', label: 'Difference', type: 'money' },
            { key: 'status', label: 'Status', sortable: true },
            { key: 'created_at', label: 'Created At', type: 'date', sortable: true },
        ],
    },
    paymentSummary: {
        title: 'Payment Mode Summary Report',
        description: 'Sales and due collections grouped by payment mode for daily reconciliation.',
        fileName: 'payment_summary_report',
        icon: 'payment',
        useReportMutation: useGetPaymentSummaryReportMutation,
        defaultSort: 'total_amount',
        summaryFields: [
            { key: 'methods', label: 'Rows', type: 'number' },
            { key: 'transaction_count', label: 'Transactions', type: 'number' },
            { key: 'total_amount', label: 'Total Amount', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'source_type', label: 'Source' },
            { key: 'payment_method', label: 'Payment Mode', sortable: true },
            { key: 'transaction_count', label: 'Transactions', type: 'number', sortable: true },
            { key: 'total_amount', label: 'Amount', type: 'money', sortable: true },
        ],
    },
    employeeSales: {
        title: 'Employee Sales / Cashier Performance Report',
        description: 'Sales, collections, discounts, and due amount by employee.',
        fileName: 'employee_sales_report',
        icon: 'employee',
        useReportMutation: useGetEmployeeSalesReportMutation,
        defaultSort: 'gross_sales',
        summaryFields: [
            { key: 'employees', label: 'Employees', type: 'number' },
            { key: 'orders', label: 'Orders', type: 'number' },
            { key: 'gross_sales', label: 'Gross Sales', type: 'money' },
            { key: 'amount_collected', label: 'Collected', type: 'money' },
            { key: 'discount_amount', label: 'Discount', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'employee_name', label: 'Employee', sortable: true },
            { key: 'order_count', label: 'Orders', type: 'number', sortable: true },
            { key: 'gross_sales', label: 'Gross Sales', type: 'money', sortable: true },
            { key: 'amount_collected', label: 'Collected', type: 'money' },
            { key: 'discount_amount', label: 'Discount', type: 'money' },
            { key: 'due_amount', label: 'Due', type: 'money' },
        ],
    },
    stockMovement: {
        title: 'Stock Movement Ledger',
        description: 'Product stock in/out movement history for mismatch investigation.',
        fileName: 'stock_movement_ledger',
        icon: 'stock',
        useReportMutation: useGetStockMovementReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'movements', label: 'Movements', type: 'number' },
            { key: 'total_quantity', label: 'Quantity', type: 'number' },
            { key: 'total_amount', label: 'Amount', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'product_name', label: 'Product' },
            { key: 'movement_type', label: 'Movement Type' },
            { key: 'quantity', label: 'Quantity', type: 'number' },
            { key: 'price', label: 'Unit Price', type: 'money' },
            { key: 'total_amount', label: 'Amount', type: 'money' },
            { key: 'reference_no', label: 'Reference' },
            { key: 'reason', label: 'Reason' },
            { key: 'user_name', label: 'Created By' },
            { key: 'created_at', label: 'Created At', type: 'date', sortable: true },
        ],
    },
    discount: {
        title: 'Discount Report',
        description: 'Orders where discount was given, including cashier and customer.',
        fileName: 'discount_report',
        icon: 'discount',
        useReportMutation: useGetDiscountReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'orders', label: 'Orders', type: 'number' },
            { key: 'discount_amount', label: 'Discount', type: 'money' },
            { key: 'gross_sales', label: 'Gross Sales', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'invoice', label: 'Invoice' },
            { key: 'customer_name', label: 'Customer' },
            { key: 'user_name', label: 'Cashier' },
            { key: 'subtotal', label: 'Subtotal', type: 'money' },
            { key: 'discount_amount', label: 'Discount', type: 'money' },
            { key: 'grand_total', label: 'Total', type: 'money' },
            { key: 'created_at', label: 'Created At', type: 'date', sortable: true },
        ],
    },
    customerStatement: {
        title: 'Customer Statement Report',
        description: 'Customer due and payment statement for credit follow-up.',
        fileName: 'customer_statement_report',
        icon: 'statement',
        useReportMutation: useGetCustomerStatementReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'entries', label: 'Entries', type: 'number' },
            { key: 'debit', label: 'Due', type: 'money' },
            { key: 'credit', label: 'Paid', type: 'money' },
            { key: 'balance', label: 'Balance', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'party_name', label: 'Customer', sortable: true },
            { key: 'entry_type', label: 'Type' },
            { key: 'debit', label: 'Due', type: 'money', sortable: true },
            { key: 'credit', label: 'Paid', type: 'money', sortable: true },
            { key: 'balance', label: 'Balance', type: 'money', sortable: true },
            { key: 'status', label: 'Status' },
            { key: 'created_at', label: 'Created At', type: 'date', sortable: true },
        ],
    },
    supplierStatement: {
        title: 'Supplier Statement Report',
        description: 'Supplier purchase and payment statement for payable settlement.',
        fileName: 'supplier_statement_report',
        icon: 'statement',
        useReportMutation: useGetSupplierStatementReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'entries', label: 'Entries', type: 'number' },
            { key: 'debit', label: 'Purchase', type: 'money' },
            { key: 'credit', label: 'Paid', type: 'money' },
            { key: 'balance', label: 'Balance', type: 'money' },
        ],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'party_name', label: 'Supplier', sortable: true },
            { key: 'entry_type', label: 'Type' },
            { key: 'debit', label: 'Purchase', type: 'money', sortable: true },
            { key: 'credit', label: 'Paid', type: 'money', sortable: true },
            { key: 'balance', label: 'Balance', type: 'money', sortable: true },
            { key: 'status', label: 'Status' },
            { key: 'created_at', label: 'Created At', type: 'date', sortable: true },
        ],
    },
    transferLedger: {
        title: 'Transfer Ledger Report',
        description: 'Store-to-store stock transfer history with status, quantity, and timestamps.',
        fileName: 'transfer_ledger_report',
        icon: 'transfer',
        useReportMutation: useGetTransferLedgerReportMutation,
        defaultSort: 'created_at',
        summaryFields: [
            { key: 'transfers', label: 'Transfers', type: 'number' },
            { key: 'items', label: 'Items', type: 'number' },
            { key: 'quantity', label: 'Quantity', type: 'number' },
        ],
        fields: [
            { key: 'from_store', label: 'From Store' },
            { key: 'to_store', label: 'To Store' },
            { key: 'status', label: 'Status', sortable: true },
            { key: 'item_count', label: 'Items', type: 'number' },
            { key: 'total_quantity', label: 'Quantity', type: 'number' },
            { key: 'created_by', label: 'Created By' },
            { key: 'shipped_at', label: 'Shipped At', type: 'date' },
            { key: 'received_at', label: 'Received At', type: 'date' },
            { key: 'created_at', label: 'Created At', type: 'date', sortable: true },
        ],
    },
    auditActivity: {
        title: 'Void / Cancel / Delete Audit Report',
        description: 'Sensitive activity history for investigation and accountability.',
        fileName: 'audit_activity_report',
        icon: 'audit',
        useReportMutation: useGetAuditActivityReportMutation,
        defaultSort: 'created_at',
        summaryFields: [{ key: 'events', label: 'Events', type: 'number' }],
        fields: [
            { key: 'store_name', label: 'Store', sortable: true },
            { key: 'actor_name', label: 'User' },
            { key: 'action', label: 'Action' },
            { key: 'entity_type', label: 'Entity' },
            { key: 'entity_id', label: 'Entity ID', type: 'number' },
            { key: 'entity_label', label: 'Reference' },
            { key: 'ip_address', label: 'IP Address' },
            { key: 'created_at', label: 'Created At', type: 'date', sortable: true },
        ],
    },
} satisfies Record<string, OperationalReportConfig>;
