import { MetadataRoute } from 'next';
import { getAppUrl } from '@/lib/seo-config';

export default function robots(): MetadataRoute.Robots {
    const baseUrl = getAppUrl();
    const disallow = [
        '/api/',
        '/admin/',
        '/private/',
        '/protected/',
        '/platform/',
        '/account/',
        '/accounting/',
        '/analytics/',
        '/audit-logs',
        '/brand/',
        '/business-os',
        '/cash-closing',
        '/cash-drawer/',
        '/category/',
        '/company/',
        '/compliance-calendar',
        '/coupons',
        '/customers/',
        '/dashboard/',
        '/data-export',
        '/ecommerce/',
        '/employees/',
        '/expenses/',
        '/feedbacks/',
        '/fiscal-compliance',
        '/font-icons',
        '/hr/',
        '/label',
        '/manual-payments',
        '/notifications/',
        '/orders/',
        '/pay/',
        '/petty-cash',
        '/pos',
        '/products/',
        '/purchases/',
        '/reports/',
        '/roles/',
        '/service-jobs',
        '/stock-transfers',
        '/store/',
        '/subscription',
        '/suppliers/',
        '/unauthorized',
        '/users/',
        '/affiliate/portal',
        '/affiliate/admin',
        '/login',
        '/register',
        '/forgot-password',
        '/reset-password',
        '/offline',
    ];

    return {
        rules: [
            {
                userAgent: '*',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'Googlebot',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'Bingbot',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'GPTBot',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'ChatGPT-User',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'PerplexityBot',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'ClaudeBot',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'anthropic-ai',
                allow: '/',
                disallow,
            },
            {
                userAgent: 'CCBot',
                allow: '/',
                disallow,
            },
        ],
        sitemap: `${baseUrl}/sitemap.xml`,
        host: baseUrl,
    };
}
